### ISSUE TITLE
Error detected while processing /Users/mixel/.vim/bundle/vim-swift/syntax/swift.vim: invalid character after \@

### ISSUE THREAD

**Issue by mxl** [kballard/vim-swift#3]
Opening vim shows this error:

```
Error detected while processing /Users/mixel/.vim/bundle/vim-swift/syntax/swift.vim:
line   99:
E59: invalid character after \@
E475: Invalid argument: swiftKeyword /\.\@1<=\%(Type\|Protocol\)\>/ display
line  214:
E59: invalid character after \@
E475: Invalid argument: swiftStdlibFunction /\<\%(\.\@1<!\|\%(\.\@1<!Swift\.\)\@6<=\)\%(abs\|advance\|alignof\|alignofValue\|asse
rt\|assertionFailure\|contains\|count\|debugPrint\|debugPrintln\|distance\|dropFirst\|dropLast\|dump\|enumerate\|equal\|extend\|f
atalError\|filter\|find\|first\|getVaList\|indices\|insert\|isEmpty\|isUniquelyReferenced\|isUniquelyReferencedNonObjC\|join\|las
t\|lazy\|lexicographicalCompare\|map\|max\|maxElement\|min\|minElement\|numericCast\|overlaps\|partition\|precondition\|precondit
ionFailure\|prefix\|print\|println\|reduce\|reflect\|removeAll\|removeAtIndex\|removeLast\|removeRange\|reverse\|sizeof\|sizeofVa
lue\|sort\|sorted\|splice\|split\|startsWith\|stride\|strideof\|strideofValue\|suffix\|swap\|toDebugString\|toString\|transcode\|
underestimateCount\|unsafeAddressOf\|unsafeBitCast\|unsafeDowncast\|unsafeUnwrap\|withExtendedLifetime\|withUnsafeMutablePointer\
|withUnsafeMutablePointers\|withUnsafePointer\|withUnsafePointers\|withVaList\|zip\|anyGenerator\|readLine\)\>\ze(/ displ
line  246:
E59: invalid character after \@
E475: Invalid argument: swiftStringEscapeUnicodeError start=/\_X\|{\@1<=\x\{8}\zs\_[^}]/ end=/}/ display contained
line  266:
E59: invalid character after \@
E475: Invalid argument: swiftLibraryValue /\.\@1<!\<Process\>/
line  268:
E59: invalid character after \@
E475: Invalid argument: swiftLibraryEnumValue /\.\@1<=\%(Some\ze(\|None\>\)/
Swift string interpolations do not work well with 'showmatch'
It is recommended that you turn it off and use matchparen instead
```

**Comment by lilyball** [comment]
> `E59: invalid character after \@`

That's odd. What version of Vim are you using?

> `Swift string interpolations do not work well with 'showmatch'
> It is recommended that you turn it off and use matchparen instead`

This is a warning emitted by the swift plugin itself. The `'showmatch'` setting does not handle Swift string interpolation at all correctly, because it ignores the `\(` and therefore tries to match the closing `)` against other parens. It's rather annoying. The built-in `matchparen` plugin is better about this.

**Comment by lilyball** [comment]
Looks like `\@123<!` was introduced in Vim 7.3.1088.

**Comment by lilyball** [comment]
113adc20efe5364460b90770777bbbae63bc7890 should fix this issue. Please let me know if anything else doesn't work.

**Comment by mxl** [comment]
I have Vim that comes with OS X. 

```
vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2014 21:00:28)
```

Your fix solved the issue, thanks.

**Comment by lilyball** [comment]
I completely forgot that OS X ships with Vim 7.3.

I highly recommend installing a newer version. You can get MacVim at the same time, which is pretty nice. You can install it easily with [Homebrew](http://brew.sh) using `brew install macvim --override-system-vim` (the `--override-system-vim` flag makes it include `vi`, `vim`, `vimdiff`, `view`, and `vimex`; without that flag it just includes all the `m*` and `g*` binaries like `mvim`).

**Comment by mxl** [comment]
Thanks for `--override-system-vim`. I thought that macvim package includes `vim` binary and was surprised when found that I'm using OS X vim.
If you have [Hombrew-Cask](https://github.com/caskroom/homebrew-cask) installed (if not - `brew install caskroom/cask/brew-cask`) then better install macvim from here - `brew cask install macvim --override-system-vim` because it also links it to `~/Applications` directory, so you can open app from Spotlight and Finder (Open With).

**Comment by lilyball** [comment]
Is that any better than just using `brew linkapps` (which will stuff a symlink into `/Applications`, as opposed to `~/Applications` that you say Homebrew-Cask uses)?

**Comment by mxl** [comment]
Sorry, forgot about `brew linkapps`. It's the same so ignore my comment above.
